#!/bin/sh

# Description: Prints some information about the environment.

echo "$SUBCOMMANDER called $0 with arguments:"
echo $1
echo $2
echo $3
echo $4
echo $5
echo $6
echo $7
echo $8
pwd
echo
echo Environment:
printenv | sort
