#!/bin/sh
# Description: Sets up tab-completion for $0, run for instructions
set -e

# FIXME: take args to do completion for different shells.

# FIXME: enable multi-level completion

sc_exec_path="$(dirname $0)"

echo "complete -W \"\c"
$SC_MAIN help --porcelain | sed -e 's/:.*//' | while read cmd; do
	echo "$cmd \c"
done
echo "\" $SC_MAIN"
echo '# Add to .bashrc: eval `'"$SC_MAIN"' completion`'
