#!/bin/sh
# Description: Sets up tab-completion for $0, run for instructions
set -e

# FIXME: take args to do completion for different shells.

# FIXME: enable multi-level completion

sc_exec_path="$(dirname $0)"

echo "complete -W \"\c"
for f in "$sc_exec_path"/*; do
	[ -d "$f" ] && continue
	[ -x "$f" ] || continue
	echo `basename "$f"`" \c"
done
echo "\" $SC_MAIN"
echo '# Add to .bashrc: eval `'"$SC_MAIN"' completion`'
