#!/bin/sh
# Description: Lists the available sub-commands (this text)
set -e

# This script discovers the short descriptive text for each subcommand by
# searching for text within the first 10 lines of each script following
# "desc[ription]", optionally with a trailing : or =.

# Calling:
# 	$SC_NAME help command
# is equivalent to:
# 	$SC_NAME command --help

sc_exec_path="$(dirname $0)"

if [ "$1" ]; then
	command="$1"
	shift
	exec "$sc_exec_path/$command" --help "$@"
else
	echo "Available $SUBCOMMANDER commands are:"
	for f in "$sc_exec_path"/*; do
		[ -d "$f" ] && continue
		[ -x "$f" ] || continue
		printf \
			"   %-10s %s\n" \
			"`basename \"$f\"`" \
			"`sed -n 's/\$0/'$SUBCOMMANDER'/g;1,10s/^.\{0,4\}desc\(ription\)\?\s*[:=]\s*//Ip' \"$f\"`"
	done
fi
