#!/bin/sh

# Description: Prints some information about the environment.
echo
echo "# The name of the subcommander-based tool:"
echo "SUBCOMMANDER=$SUBCOMMANDER"
echo
echo "# The location where its subcommands live:"
echo "SC_EXEC_PATH=$SC_EXEC_PATH"
if [ $verbose ]; then
	echo
	echo "# The environment variable holding the context:"
	echo "SC_CTX_ENVNAME=$SC_CTX_ENVNAME"
fi
echo
eval "context=\$$SC_CTX_ENVNAME"
if [ "$context" ]; then
echo "# The current context:"
echo "$SC_CTX_ENVNAME=$context"
else
	echo "# There is no current context defined. Or as git would say,"
	echo "fatal: Not a $SUBCOMMANDER workspace (or any of the parent directories): .$SUBCOMMANDER.context"
	exit 1
fi
