#!/bin/sh
# Description: Initializes a directory for use with $0

#
# subcommander/lib/init - initializes a directory; for use with subcommander
#
# Copyright 2014  Michael F. Lamb <http://datagrok.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# License: GPLv3 http://www.gnu.org/licenses/gpl.html
#

set -e

context_file=".$SC_MAIN.context"

if [ "$1" = "--help" ]; then
	fmt <<- EOF
		Usage: $SC_MAIN $0 [DIRECTORY]

		Mark the DIRECTORY for use as a workspace for $SC_MAIN.

		Directories are $SC_MAIN workspaces if they contain a file
		$context_file. $SC_MAIN executes this file for every invocation.
	EOF
	exit
fi

if [ "$1" ]; then
	mkdir -p "$1"
	cd "$1"
	shift
fi

context_dir=`pwd -P`

if [ -e "$context_file" ]; then
	echo "$context_dir is already a $SC_MAIN workspace."
	echo "(Context for $SC_MAIN already exists: $context_dir/$context_file)"
	exit 1
else
	echo "Marking $context_dir as a $SC_MAIN workspace."
	echo "(Initializing context for $SC_MAIN as $context_dir/$context_file)"
	cat > "$context_file" <<-EOF
		#!/bin/sh
		# This file is executed by '$SC_MAIN' every time you run a '$SC_MAIN'
		# command. The mere existence of a file with this name marks this
		# directory and every directory within as a workarea or 'context' for
		# '$SC_MAIN'. This means you can edit this script, or replace it with
		# your own executable script or compiled program, so long as you take
		# care to exec() the command passed in as arguments, as is done below.

		# If you have hooks to execute or customizations to make to the
		# environment, you may do so here.

		exec "\$@"
		# Execution never returns from 'exec'; this line will never be reached.
	EOF
	chmod +x "$context_file"
fi
